# Generated by Django 2.2.2 on 2019-06-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('serial_number', models.CharField(max_length=256)),
                ('price', models.IntegerField(blank=True)),
            ],
        ),
    ]
